version: '3.2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=hakaru-db
    ports:
      - 13306:3306