version: '3.2'
services:
  mysql:
    build: ./db
    volumes:
      - "./db/sql:/docker-entrypoint-initdb.d"
      - "./db/conf:/etc/mysql/conf.d"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=hakaru-db
    ports:
      - 13306:3306